#!/bin/bash
# AUTO-GENERATED by scripts/render-configs.py — edit models.yaml instead
set -e

exec infinity_emb v2 \
  --served-model-name "/models/BAAI/bge-m3" \
  --served-model-name "/models/BAAI/bge-reranker-v2-m3" \
  --port 7997 \
  --engine torch \
  --dtype float16 \
  --batch-size 64 \
  --device cuda
