#!/usr/bin/env python3
"""
scripts/render-configs.py — Generate service configs from models.yaml

Generates:
  litellm/config.yaml      (model_list + static settings from config.template.yaml)
  ollama/init-models.sh    (pull script for Ollama)
  infinity/entrypoint.sh   (startup command for Infinity embedding/reranker server)

Usage:
  python3 scripts/render-configs.py
  ./deploy.sh render
"""
import sys
import os
from pathlib import Path

ROOT = Path(__file__).parent.parent


def load_yaml(path: Path) -> dict:
    try:
        import yaml
    except ImportError:
        print("ERROR: PyYAML not installed. Run: pip3 install pyyaml", file=sys.stderr)
        sys.exit(1)
    with open(path) as f:
        return yaml.safe_load(f)


def render_litellm_config(models: dict) -> None:
    template_path = ROOT / "litellm" / "config.template.yaml"
    if not template_path.exists():
        print(f"ERROR: {template_path} not found", file=sys.stderr)
        sys.exit(1)

    lines = [
        "# AUTO-GENERATED by scripts/render-configs.py\n",
        "# Source: models.yaml + litellm/config.template.yaml\n",
        "# To edit models: modify models.yaml then run: ./deploy.sh render\n",
        "# To edit proxy settings: modify litellm/config.template.yaml\n",
        "\n",
        "model_list:\n",
    ]

    # Chat models (via Ollama)
    chat_models = models.get("chat", [])
    if chat_models:
        lines.append("\n  # ── CHAT / COMPLETION models via Ollama ──────────────────────────────\n")
        for m in chat_models:
            desc = m.get("description", m["name"])
            ollama_model = m["ollama_model"]
            timeout = m.get("timeout", 300)
            stream_timeout = m.get("stream_timeout", 300)

            lines.append(f"\n  # {desc}\n")
            lines.append(f"  - model_name: {m['name']}\n")
            lines.append(f"    litellm_params:\n")
            lines.append(f"      model: ollama_chat/{ollama_model}\n")
            lines.append(f"      api_base: http://ollama:11434\n")
            lines.append(f"      stream_timeout: {stream_timeout}\n")
            lines.append(f"      timeout: {timeout}\n")

            for alias in m.get("aliases", []):
                lines.append(f"\n  - model_name: {alias}\n")
                lines.append(f"    litellm_params:\n")
                lines.append(f"      model: ollama_chat/{ollama_model}\n")
                lines.append(f"      api_base: http://ollama:11434\n")

    # Embedding models (via Infinity)
    embedding_models = models.get("embedding", [])
    if embedding_models:
        lines.append("\n  # ── EMBEDDING models via Infinity ────────────────────────────────────\n")
        for m in embedding_models:
            served = m["local_path"]
            lines.append(f"\n  - model_name: {m['name']}\n")
            lines.append(f"    litellm_params:\n")
            lines.append(f"      model: openai/{served}\n")
            lines.append(f"      api_base: http://infinity:7997/v1\n")
            for alias in m.get("aliases", []):
                lines.append(f"\n  - model_name: {alias}\n")
                lines.append(f"    litellm_params:\n")
                lines.append(f"      model: openai/{served}\n")
                lines.append(f"      api_base: http://infinity:7997/v1\n")

    # Reranker models (via Infinity)
    reranker_models = models.get("reranker", [])
    if reranker_models:
        lines.append("\n  # ── RERANKER models via Infinity ─────────────────────────────────────\n")
        for m in reranker_models:
            served = m["local_path"]
            lines.append(f"\n  - model_name: {m['name']}\n")
            lines.append(f"    litellm_params:\n")
            lines.append(f"      model: openai/{served}\n")
            lines.append(f"      api_base: http://infinity:7997/v1\n")
            for alias in m.get("aliases", []):
                lines.append(f"\n  - model_name: {alias}\n")
                lines.append(f"    litellm_params:\n")
                lines.append(f"      model: openai/{served}\n")
                lines.append(f"      api_base: http://infinity:7997/v1\n")

    lines.append("\n")
    with open(template_path) as f:
        lines.append(f.read())

    out = ROOT / "litellm" / "config.yaml"
    out.write_text("".join(lines))
    print(f"  [OK] {out.relative_to(ROOT)}")


def render_ollama_init(models: dict) -> None:
    chat_models = models.get("chat", [])
    lines = [
        "#!/bin/bash\n",
        "# AUTO-GENERATED by scripts/render-configs.py — edit models.yaml instead\n",
        "set -e\n",
        "\n",
        'OLLAMA_HOST="${OLLAMA_HOST:-http://ollama:11434}"\n',
        "\n",
        'echo "==> Waiting for Ollama at ${OLLAMA_HOST}..."\n',
        'until curl -sf "${OLLAMA_HOST}/api/tags" > /dev/null; do\n',
        "  sleep 5\n",
        "done\n",
        "\n",
    ]

    for m in chat_models:
        desc = m.get("description", m["name"])
        lines.append(f'echo "==> Pulling {m["ollama_model"]}  ({desc})"\n')
        lines.append(f'ollama pull {m["ollama_model"]}\n')
        lines.append("\n")

    lines.append('echo "==> Done. Loaded models:"\n')
    lines.append("ollama list\n")

    out = ROOT / "ollama" / "init-models.sh"
    out.write_text("".join(lines))
    out.chmod(0o755)
    print(f"  [OK] {out.relative_to(ROOT)}")


def render_infinity_entrypoint(models: dict) -> None:
    inf = models.get("infinity", {})
    port = inf.get("port", 7997)
    engine = inf.get("engine", "torch")
    dtype = inf.get("dtype", "float16")
    batch_size = inf.get("batch_size", 64)
    device = inf.get("device", "cuda")

    all_models = list(models.get("embedding", [])) + list(models.get("reranker", []))

    lines = [
        "#!/bin/bash\n",
        "# AUTO-GENERATED by scripts/render-configs.py — edit models.yaml instead\n",
        "set -e\n",
        "\n",
        "exec infinity_emb v2 \\\n",
    ]

    for m in all_models:
        local_path = m["local_path"]
        lines.append(f'  --served-model-name "{local_path}" \\\n')

    lines.append(f"  --port {port} \\\n")
    lines.append(f"  --engine {engine} \\\n")
    lines.append(f"  --dtype {dtype} \\\n")
    lines.append(f"  --batch-size {batch_size} \\\n")
    lines.append(f"  --device {device}\n")

    out = ROOT / "infinity" / "entrypoint.sh"
    out.write_text("".join(lines))
    out.chmod(0o755)
    print(f"  [OK] {out.relative_to(ROOT)}")


def main() -> None:
    models_path = ROOT / "models.yaml"
    if not models_path.exists():
        print(f"ERROR: {models_path} not found", file=sys.stderr)
        sys.exit(1)

    models = load_yaml(models_path)
    print("Rendering configs from models.yaml ...")

    render_litellm_config(models)
    render_ollama_init(models)
    render_infinity_entrypoint(models)

    print("")
    print("Done. Apply changes with:")
    print("  docker compose restart litellm          # after chat/embedding/reranker changes")
    print("  docker compose restart infinity         # after embedding/reranker changes")
    print("  docker compose restart ollama-init      # to pull new Ollama models")


if __name__ == "__main__":
    main()
