#!/usr/bin/env python3
"""
scripts/render-configs.py — Generate service configs from models.yaml

Generates:
  litellm/config.yaml      (model_list + static settings from config.template.yaml)
  ollama/init-models.sh    (pull script for Ollama)

Usage:
  python3 scripts/render-configs.py
  ./deploy.sh render
"""
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent


def load_yaml(path: Path) -> dict:
    try:
        import yaml
    except ImportError:
        print("ERROR: PyYAML not installed. Run: pip3 install pyyaml", file=sys.stderr)
        sys.exit(1)
    with open(path) as f:
        return yaml.safe_load(f)


def render_litellm_config(models: dict) -> None:
    template_path = ROOT / "litellm" / "config.template.yaml"
    if not template_path.exists():
        print(f"ERROR: {template_path} not found", file=sys.stderr)
        sys.exit(1)

    lines = [
        "# AUTO-GENERATED by scripts/render-configs.py\n",
        "# Source: models.yaml + litellm/config.template.yaml\n",
        "# To edit models: modify models.yaml then run: ./deploy.sh render\n",
        "# To edit proxy settings: modify litellm/config.template.yaml\n",
        "\n",
        "model_list:\n",
    ]

    chat_models = models.get("chat", [])
    if chat_models:
        lines.append("\n  # ── CHAT / COMPLETION models via Ollama ──────────────────────────────\n")
        for m in chat_models:
            desc = m.get("description", m["name"])
            ollama_model = m["ollama_model"]
            timeout = m.get("timeout", 300)
            stream_timeout = m.get("stream_timeout", 300)

            lines.append(f"\n  # {desc}\n")
            lines.append(f"  - model_name: {m['name']}\n")
            lines.append(f"    litellm_params:\n")
            lines.append(f"      model: ollama_chat/{ollama_model}\n")
            lines.append(f"      api_base: http://ollama:11434\n")
            lines.append(f"      stream_timeout: {stream_timeout}\n")
            lines.append(f"      timeout: {timeout}\n")

            for alias in m.get("aliases", []):
                lines.append(f"\n  - model_name: {alias}\n")
                lines.append(f"    litellm_params:\n")
                lines.append(f"      model: ollama_chat/{ollama_model}\n")
                lines.append(f"      api_base: http://ollama:11434\n")

    lines.append("\n")
    with open(template_path) as f:
        lines.append(f.read())

    out = ROOT / "litellm" / "config.yaml"
    out.write_text("".join(lines))
    print(f"  [OK] {out.relative_to(ROOT)}")


def render_ollama_init(models: dict) -> None:
    chat_models = models.get("chat", [])
    lines = [
        "#!/bin/bash\n",
        "# AUTO-GENERATED by scripts/render-configs.py — edit models.yaml instead\n",
        "set -e\n",
        "\n",
        'OLLAMA_HOST="${OLLAMA_HOST:-http://ollama:11434}"\n',
        "\n",
        'echo "==> Waiting for Ollama at ${OLLAMA_HOST}..."\n',
        'until ollama list > /dev/null 2>&1; do\n',
        "  sleep 5\n",
        "done\n",
        "\n",
    ]

    for m in chat_models:
        desc = m.get("description", m["name"])
        lines.append(f'echo "==> Pulling {m["ollama_model"]}  ({desc})"\n')
        lines.append(f'ollama pull {m["ollama_model"]}\n')
        lines.append("\n")

    lines.append('echo "==> Done. Loaded models:"\n')
    lines.append("ollama list\n")

    out = ROOT / "ollama" / "init-models.sh"
    out.write_text("".join(lines))
    out.chmod(0o755)
    print(f"  [OK] {out.relative_to(ROOT)}")


def main() -> None:
    models_path = ROOT / "models.yaml"
    if not models_path.exists():
        print(f"ERROR: {models_path} not found", file=sys.stderr)
        sys.exit(1)

    models = load_yaml(models_path)
    print("Rendering configs from models.yaml ...")

    render_litellm_config(models)
    render_ollama_init(models)

    print("")
    print("Done. Apply changes with:")
    print("  docker compose restart litellm     # after model changes")
    print("  docker compose restart ollama-init # to pull new Ollama models")


if __name__ == "__main__":
    main()
