#!/bin/bash
# AUTO-GENERATED by scripts/render-configs.py — edit models.yaml instead
set -e

OLLAMA_HOST="${OLLAMA_HOST:-http://ollama:11434}"

echo "==> Waiting for Ollama at ${OLLAMA_HOST}..."
until curl -sf "${OLLAMA_HOST}/api/tags" > /dev/null; do
  sleep 5
done

echo "==> Pulling qwen3.6:27b  (Qwen 3.6 27B — 17 GB VRAM, 256K context, text + vision)"
ollama pull qwen3.6:27b

echo "==> Done. Loaded models:"
ollama list
